config/routes.rb
Rails.application.routes.draw do
  

  # 安卓接口
  get 'people/get_one_data'
  get 'people/get_data'
  post 'people/save_data'
  post 'people/remove'
  post 'people/update_data'
  resources :people

  root 'static_pages#home'
  # get 'home' to 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login',to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets ,only: [:new,:edit,:create,:update]
  resources :microposts ,only: [:create,:destroy]
  resources :comments ,only: [:create,:destroy]
  resources :relationships ,only: [:create,:destroy]
  resources :dots ,only: [:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "app/loggin", to: 'apps#loggin'
  get "app/feed", to: 'apps#feed'
  post "app/seedmicropost", to: 'apps#seedmicropost'
  post "app/register", to: 'apps#register'
  post "app/dot", to: 'apps#dot'
  post "app/dotDestroy",to: 'apps#dotDestroy'
  get "app/getCommit", to: 'apps#getCommit'
  get "app/getDots", to: 'apps#getDots'
  get "app/getMicropost", to: 'apps#getMicropost'
  post "app/seedcommit", to: 'apps#seedcommit'
  get "app/getUser", to: 'apps#getUser'
  get "app/getUserMicroposts", to: 'apps#getUserMicroposts'
  post "app/unfollow", to: 'apps#unfollow'
  post "app/follow", to: 'apps#follow'
  get "app/get_follower_users", to: 'apps#get_follower_users'
  post "app/user_update", to: 'apps#user_update'
  get "app/getUserDotMicroposts", to: 'apps#getUserDotMicroposts'
  get "app/getFindMicroposts", to: 'apps#getFindMicroposts'
  post "app/micropost_destroy",to: 'apps#micropost_destroy'
  post "app/account_destroy",to: 'apps#account_destroy'
  post "app/sendmicropost", to: 'apps#sendmicropost'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  before_action :get_user,only: [:edit,:update]
  before_action :valid_user, only: [:edit,:update]
  before_action :check_expiration, only: [:edit,:update]
  def new
  end

  def edit
  end

  def create
  	@user = User.find_by(email: params[:password_reset][:email])
  	if @user
  		if @user.activated?
  			@user.create_password_reset_digest
        @user.send_reset_email
	  		flash[:info] = "Please check your email to activate your account"
	  		redirect_to root_url
	  	else
	  		message = "Account not activated."
	        message += "Check your email for the activation link"
	        flash[:warning] = message
	        redirect_to root_url
	  	end
  	else
  		flash[:danger] = 'Invalid email combination'
		  render 'new'
  		
  	end
  	
  end

  def update
    
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def get_user
      @user = User.find_by(email: params[:email])
    end

    def user_params
      params.require(:user).permit(:password,:password_confirmation)
    end

    def valid_user
      unless (@user &&@user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired"
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title,"New Password") %>
<h1>New Password</h1>
<div class="row">
	<div class = "co1-md-6 co1-offset-3">
		<%= form_for(@user,url: password_reset_path(params[:id])) do |f| %>
		<%= render 'shared/error_message' ,object: f.object%>
		<%= hidden_field_tag :email,@user.email %>
		<%= f.label :password%>
		<%= f.password_field :password,class: 'form-control' %>
		<%= f.label :password_confirmation,"Confirmation"%>
		<%= f.password_field :password_confirmation ,class: 'form-control' %>


		<%= f.submit "update password",class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title,"Password Reset") %>
<h1>Password Reset</h1>
<div class="row">
	<div class = "co1-md-6 co1-offset-3">
		<%= form_for(:password_reset,url: password_resets_path) do |f| %>
		<%= f.label :email %>
		<%= f.email_field :email,class: 'form-control' %>


		<%= f.submit "Send Password Reset Email",class: "btn btn-primary" %>
		<% end %>
	</div>
</div>