config/routes.rb
Rails.application.routes.draw do
  

  # 安卓接口
  get 'people/get_one_data'
  get 'people/get_data'
  post 'people/save_data'
  post 'people/remove'
  post 'people/update_data'
  resources :people

  root 'static_pages#home'
  # get 'home' to 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login',to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets ,only: [:new,:edit,:create,:update]
  resources :microposts ,only: [:create,:destroy]
  resources :comments ,only: [:create,:destroy]
  resources :relationships ,only: [:create,:destroy]
  resources :dots ,only: [:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "app/loggin", to: 'apps#loggin'
  get "app/feed", to: 'apps#feed'
  post "app/seedmicropost", to: 'apps#seedmicropost'
  post "app/register", to: 'apps#register'
  post "app/dot", to: 'apps#dot'
  post "app/dotDestroy",to: 'apps#dotDestroy'
  get "app/getCommit", to: 'apps#getCommit'
  get "app/getDots", to: 'apps#getDots'
  get "app/getMicropost", to: 'apps#getMicropost'
  post "app/seedcommit", to: 'apps#seedcommit'
  get "app/getUser", to: 'apps#getUser'
  get "app/getUserMicroposts", to: 'apps#getUserMicroposts'
  post "app/unfollow", to: 'apps#unfollow'
  post "app/follow", to: 'apps#follow'
  get "app/get_follower_users", to: 'apps#get_follower_users'
  post "app/user_update", to: 'apps#user_update'
  get "app/getUserDotMicroposts", to: 'apps#getUserDotMicroposts'
  get "app/getFindMicroposts", to: 'apps#getFindMicroposts'
  post "app/micropost_destroy",to: 'apps#micropost_destroy'
  post "app/account_destroy",to: 'apps#account_destroy'
  post "app/sendmicropost", to: 'apps#sendmicropost'
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create

    @person = Person.new(person_params)



    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_data
    p params
    respond_to do |format|
        if Person.update(params["id"], :phone=> params["phone"], :address=>params["address"] ,:name=>params["name"])
          format.json {render json: {'status'=>"0",'data'=> Person.find(request.query_parameters["id"])} }
        else
          #format.json {render json: json_str.to_json }#如果用json字符串，则需要通过to_json转化格式返回给前台js，那么前台需要执行eval来再次转换格式  
          format.json { render json: a.errors, status: :unprocessable_entity } #此处建议使用hash格式数据返回，这样前台js就无需执行eval来转换格式
        end  
    end  
  end
  def save_data  
      p params  
      a = Person.new
      a.phone = params["phone"]
      a.address = params["address"]
      a.name = params["name"]
      respond_to do |format|
          if a.save
            format.json {render json: {'status'=>"0",'data'=> Person.last} }
          else
            #format.json {render json: json_str.to_json }#如果用json字符串，则需要通过to_json转化格式返回给前台js，那么前台需要执行eval来再次转换格式  
            format.json { render json: a.errors, status: :unprocessable_entity } #此处建议使用hash格式数据返回，这样前台js就无需执行eval来转换格式
          end  
      end  
  end  

  def get_data  
      # @person = Person.find(params["id"])
      @people = Person.all
      respond_to do |format|
        format.html { render json: {'status'=>"0",'data'=>"ok"} }
        format.json { render json: @people  }
      end 
  end 

  def get_one_data  
      p request.query_parameters 
      @person = Person.find(request.query_parameters["id"])
      respond_to do |format|
        format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
        # format.json { render json: {'status'=>"0",'data'=>@person}  }
        format.json { render json: @person }
      end 
      
  end 

  def remove
    @person = Person.find(params["id"])
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { render json: {'status'=>"0",'data'=>"ok"}  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :address, :phone)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :person_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :person_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :person_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.address %></td>
        <td><%= person.phone %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @person.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>