config/routes.rb
Rails.application.routes.draw do
  

  # 安卓接口
  get 'people/get_one_data'
  get 'people/get_data'
  post 'people/save_data'
  post 'people/remove'
  post 'people/update_data'
  resources :people

  root 'static_pages#home'
  # get 'home' to 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login',to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets ,only: [:new,:edit,:create,:update]
  resources :microposts ,only: [:create,:destroy]
  resources :comments ,only: [:create,:destroy]
  resources :relationships ,only: [:create,:destroy]
  resources :dots ,only: [:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "app/loggin", to: 'apps#loggin'
  get "app/feed", to: 'apps#feed'
  post "app/seedmicropost", to: 'apps#seedmicropost'
  post "app/register", to: 'apps#register'
  post "app/dot", to: 'apps#dot'
  post "app/dotDestroy",to: 'apps#dotDestroy'
  get "app/getCommit", to: 'apps#getCommit'
  get "app/getDots", to: 'apps#getDots'
  get "app/getMicropost", to: 'apps#getMicropost'
  post "app/seedcommit", to: 'apps#seedcommit'
  get "app/getUser", to: 'apps#getUser'
  get "app/getUserMicroposts", to: 'apps#getUserMicroposts'
  post "app/unfollow", to: 'apps#unfollow'
  post "app/follow", to: 'apps#follow'
  get "app/get_follower_users", to: 'apps#get_follower_users'
  post "app/user_update", to: 'apps#user_update'
  get "app/getUserDotMicroposts", to: 'apps#getUserDotMicroposts'
  get "app/getFindMicroposts", to: 'apps#getFindMicroposts'
  post "app/micropost_destroy",to: 'apps#micropost_destroy'
  post "app/account_destroy",to: 'apps#account_destroy'
  post "app/sendmicropost", to: 'apps#sendmicropost'
end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment,remote: true) do |f| %>
<div> <%= hidden_field_tag :micropost_id,micropost.id %> </div>
<div> <%= hidden_field_tag :commenter_id,current_user.id %> </div>
	<div class="field">
		<%= f.text_area :body,placeholder: "Compose new micropost..." %>
	</div>
	<%= f.submit "Commit",class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
	<div id = 'error_explanation'>
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count,"error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li> <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_message',object: f.object %>
	<div class="field">
		<%= f.text_area :content,placeholder: "Compose new micropost..." %>
	</div>
	<%= f.submit "Post",class: "btn btn-primary" %>
	<span class="picture">
		选择要上传的图片<%= f.file_field :picture , multiple: true,accept: 'image/jpeg,image/gif,image/png' %>
	</span>
	<span class="video">
		选择要上传的视频<%= f.file_field :video ,accept: 'video/mp4,video/mov,video/avi'%>
	</span>
<% end %>

<!-- <script type="text/javascript">
	$('#micropost_picture').bind('change',function(){
		var size_in_megabytes  = this.files[0].size/1024/1024;
		if (size_in_megabytes>5) {
			alert("Maximum file size is 5MB, please choose a smaller file.")
		}
	});
</script> -->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user,size: 50),current_user %>
<h1> <%= current_user.name %> </h1>
<span><%= link_to " view my profile",current_user %></span>
<span><%= pluralize(current_user.microposts.count,"micropost") %></span>