config/routes.rb
Rails.application.routes.draw do
  

  # 安卓接口
  get 'people/get_one_data'
  get 'people/get_data'
  post 'people/save_data'
  post 'people/remove'
  post 'people/update_data'
  resources :people

  root 'static_pages#home'
  # get 'home' to 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login',to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets ,only: [:new,:edit,:create,:update]
  resources :microposts ,only: [:create,:destroy]
  resources :comments ,only: [:create,:destroy]
  resources :relationships ,only: [:create,:destroy]
  resources :dots ,only: [:create,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "app/loggin", to: 'apps#loggin'
  get "app/feed", to: 'apps#feed'
  post "app/seedmicropost", to: 'apps#seedmicropost'
  post "app/register", to: 'apps#register'
  post "app/dot", to: 'apps#dot'
  post "app/dotDestroy",to: 'apps#dotDestroy'
  get "app/getCommit", to: 'apps#getCommit'
  get "app/getDots", to: 'apps#getDots'
  get "app/getMicropost", to: 'apps#getMicropost'
  post "app/seedcommit", to: 'apps#seedcommit'
  get "app/getUser", to: 'apps#getUser'
  get "app/getUserMicroposts", to: 'apps#getUserMicroposts'
  post "app/unfollow", to: 'apps#unfollow'
  post "app/follow", to: 'apps#follow'
  get "app/get_follower_users", to: 'apps#get_follower_users'
  post "app/user_update", to: 'apps#user_update'
  get "app/getUserDotMicroposts", to: 'apps#getUserDotMicroposts'
  get "app/getFindMicroposts", to: 'apps#getFindMicroposts'
  post "app/micropost_destroy",to: 'apps#micropost_destroy'
  post "app/account_destroy",to: 'apps#account_destroy'
  post "app/sendmicropost", to: 'apps#sendmicropost'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The <a herf="http://www.railstutor.org/"> Ruby on Rails Tutorial</a>
		by <a herf="www.baidu.com">Li zheng</a>
	</small>
	<nav>
		<ul>
			<li> <%= link_to "About","https://github.com/robotwai/rails_demo_post"%></li>
			
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  		<div>
  			<%= link_to "Free Feed", root_path,id: "logo" %>
  			<nav>
  				<ul class = "nav navbar-nav navbar-right">
  					<li><%= link_to "Home",root_path %></li>
  					<li><%= link_to "Help", help_path%></li>
            <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
  				</ul>
  			</nav>
  		</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all" %>  
	<%= javascript_include_tag "application" %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> </title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
      <% flash.each do |message_type,message| %>
        <div class = "alert alert-<%= message_type %>"> <%= message %></div>
      <% end %>
    	<%= yield %>
    	<%= render 'layouts/footer' %>
    	<%= debug(params) if Rails.env.development? %>
	</div>
  </body>
</html>